version: "3"

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:alpine
    command: --docker --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml:ro
    ports:
      - 8000:80
      - 8080:8080
    labels:
      - traefik.frontend.rule=Host:monitor.example.com
      - traefik.port:8080
      - traefik.docker.network=proxy
    networks:
      - proxy

  service1:
    image:  jwilder/whoami
    labels:
      - traefik.backend=service1
      - traefik.frontend.rule=Host:service1.example.com
      - traefik.docker.network=proxy
      - traefik.port=8000
    networks:
      - proxy

  service2:
    image: jwilder/whoami
    labels:
      - traefik.backend=service2
      - traefik.frontend.rule=Host:service2.example.com
      - traefik.docker.network=proxy
      - traefik.port=8000
    networks:
      - proxy
